---
kind: pipeline
type: exec
name: replica.one

clone:
  depth: 25

steps:
  - name: submodules
    commands:
      - git submodule update --init --recursive --depth 25

  - name: makeDirectoryStructure
    commands:
      - echo $${DRONE_BRANCH} | iconv -t ascii//TRANSLIT | sed -r s/[~\^]+//g | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z > branchName
      - mkdir $(cat branchName)
      - date '+%Y-%m-%d' > dateDirectory


# Templates
  - name: buildTemplate
    nodeinfo: &buildTemplate
      environment:
        CTARGET: architecture
        target: target
        TARGET_DISTRO: gentoo
      commands:
        - cd .. && mkdir replica-$${target}-$${CTARGET}-$${TARGET_DISTRO}
        - cd replica-$${target}-$${CTARGET}-$${TARGET_DISTRO}
        - cp -a ../src/. ./
        - make V=1 J=$(($(nproc) + 1)) package_$${target}
        - mkdir -p ./$${target}/$(cat dateDirectory)
        - cp -a ./output/. ./$${target}/$(cat dateDirectory)/
        - rsync -a ./$${target} ../src/$(cat branchName)/

       
  - name: buildTemplateNoOutput
    nodeinfo: &buildTemplateNoOutput
      environment:
        CTARGET: architecture
        target: target
        TARGET_DISTRO: gentoo
      commands:
        - cd .. && mkdir replica-$${target}-$${CTARGET}-$${TARGET_DISTRO}
        - cd replica-$${target}-$${CTARGET}-$${TARGET_DISTRO}
        - cp -a ../src/. ./
        - make V=1 J=$(($(nproc) + 1)) package_$${target}

  
  - name: artifactsTemplate
    nodeinfo: &artifactsTemplate
      environment:
        DRONE_USER:
          from_secret: droneUser
        DRONE_PASSWORD:
          from_secret: dronePassword
        DRONE_SERVER:
          from_secret: droneServer
        DRONE_DIRECTORY_PATH:
          from_secret: droneDirectoryPath
        DRONE_RELEASES_PATH:
          from_secret: droneReleasesPath


# Toolchain targets
  - name: arm64:vm-test
    <<: *buildTemplate
    environment:
      CTARGET: aarch64-unknown-linux-gnu
      target: vm-test

  - name: amd64:vm-test
    <<: *buildTemplate
    environment:
      CTARGET: x86_64-multilib-linux-gnu
      target: vm-test
  

# Transfer Artifacts
  - name: transferArtifacts
    <<: *artifactsTemplate
    commands: 
      - echo -e $${DRONE_PASSWORD} | openssl base64 -A -d > ./key
      - chmod 600 ./key
      - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentityFile=./key -r $(cat branchName) $${DRONE_USER}@$${DRONE_SERVER}:$${DRONE_DIRECTORY_PATH}

  - name: transferReleases
    <<: *artifactsTemplate
    commands:
      - echo -e $${DRONE_PASSWORD} | openssl base64 -A -d > ./key
      - chmod 600 ./key
      - cp -r $(cat branchName) $${DRONE_TAG}
      - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentityFile=./key -r $${DRONE_TAG} $${DRONE_USER}@$${DRONE_SERVER}:$${DRONE_RELEASES_PATH}
    when:
      event:
      - tag   
