---
kind: pipeline
type: exec
name: replica.one

clone:
  depth: 25

steps:
  - name: submodules
    commands:
      - git submodule update --init --recursive --depth 25

  - name: makeDirectoryStructure
    commands:
      - echo $${DRONE_BRANCH} | iconv -t ascii//TRANSLIT | sed -r s/[~\^]+//g | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z > branchName
      - mkdir $(cat branchName)
      - date '+%Y-%m-%d' > dateDirectory
      - cd $(cat branchName)
      - mkdir $(cat ../dateDirectory)
      - cd $(cat ../dateDirectory)
      - mkdir armv7a-unknown-linux-gnueabihf aarch64-unknown-linux-gnu x86_64-multilib-linux-gnu
      - mkdir armv7a-unknown-linux-musleabihf aarch64-unknown-linux-musl x86_64-multilib-linux-musl

# Build templates
  - name: buildTemplate
    nodeinfo: &buildTemplate
      environment:
        CTARGET: architecture
        target: target
      commands:
        - make V=1 J=$(($(nproc) + 1)) package_$${target}
        - mkdir $${target}
        - mv ./output/* ./$${target}
        - mv ./$${target} ./$(cat branchName)/$(cat dateDirectory)/$${CTARGET}
   
  - name: buildTemplateNoOutput
    nodeinfo: &buildTemplateNoOutput
      environment:
        CTARGET: architecture
        target: target
      commands:
        - make V=1 J=$(($(nproc) + 1)) package_$${target}


# Toolchain targets
  - name: arm:toolchain
    <<: *buildTemplate
    environment:
      CTARGET: armv7a-unknown-linux-gnueabihf
      target: toolchain

  - name: arm64:toolchain
    <<: *buildTemplate
    environment:
      CTARGET: aarch64-unknown-linux-gnu
      target: toolchain

  - name: amd64:toolchain
    <<: *buildTemplate
    environment:
      CTARGET: x86_64-multilib-linux-gnu
      target: toolchain
  
  - name: arm-musl:toolchain
    <<: *buildTemplate
    environment:
      CTARGET: armv7a-unknown-linux-musleabihf
      target: toolchain
   
  - name: arm64-musl:toolchain
    <<: *buildTemplate
    environment:
      CTARGET: aarch64-unknown-linux-musl
      target: toolchain

  - name: amd64-musl:toolchain
    <<: *buildTemplate
    environment:
      CTARGET: x86_64-multilib-linux-musl
      target: toolchain
  

# Device targets
  - name: amd64:server-services
    <<: *buildTemplate
    environment:
      CTARGET: x86_64-multilib-linux-gnu
      target: server-services

# System targets
  - name: arm:system
    <<: *buildTemplateNoOutput
    environment:
      CTARGET: armv7a-unknown-linux-gnueabihf
      target: system

  - name: arm64:system
    <<: *buildTemplateNoOutput
    environment:
      CTARGET: aarch64-unknown-linux-gnu
      target: system

  - name: amd64:system
    <<: *buildTemplateNoOutput
    environment:
      CTARGET: x86_64-multilib-linux-gnu
      target: system

  - name: arm-musl:system
    <<: *buildTemplateNoOutput
    environment:
      CTARGET: armv7a-unknown-linux-musleabihf
      target: system

  - name: arm64-musl:system
    <<: *buildTemplateNoOutput
    environment:
      CTARGET: aarch64-unknown-linux-musl
      target: system

  - name: amd64-musl:system
    <<: *buildTemplateNoOutput
    environment:
      CTARGET: x86_64-multilib-linux-musl
      target: system

 
# File transfer 
  - name: transferArtifacts
    environment:
      DRONE_USER:
        from_secret: droneUser
      DRONE_PASSWORD:
        from_secret: dronePassword
      DRONE_SERVER:
        from_secret: droneServer
      DRONE_DIRECTORY_PATH:
        from_secret: droneDirectoryPath
    commands:
      - echo $${DRONE_BRANCH}
      #- echo -e $${DRONE_PASSWORD} | openssl base64 -A -d > ./key
      #- chmod 600 ./key
      #- scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentityFile=./key -r $(cat branchName) $${DRONE_USER}@$${DRONE_SERVER}:$${DRONE_DIRECTORY_PATH}
